#! /usr/bin/env python
# WAF build script for midori
# This file is licensed under the terms of the expat license, see the file EXPAT.

import platform

obj = bld.new_task_gen ('cc', 'staticlib')
obj.name = 'katze'
obj.target = 'katze'
obj.includes = '. ../.'
obj.find_sources_in_dirs ('.')
obj.uselib = 'GMODULE LIBSOUP GTK LIBXML'
obj.install_path = None

if platform.architecture ()[0] == '64bit':
    obj.env.append_value ('CCFLAGS', '-fPIC')
